services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.multi
    command: '/usr/local/php/sbin/php-fpm -F'
    tty: true
    stdin_open: true
    volumes:
      - php-fpm-sock:/run/php
      - doc-root:/var/www/html
  web:
    build:
      context: .
      dockerfile: Dockerfile.apache
    ports:
      - 443:443
    volumes:
      - php-fpm-sock:/run/php
      - doc-root:/var/www/html
    depends_on:
      - app
volumes:
  php-fpm-sock:
  doc-root:
